# Stage 1: Build the React app
FROM node:20 AS builder

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the app
COPY . .

# Start the React app in development mode
CMD ["npm", "start"]