version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend-nest
    command: npm run start:dev
    build:
      context: ./backend-nest
      dockerfile: dockerfile
    ports:
      - "3100:3100"
    depends_on:
      - postgres

  frontend:
    container_name: react-frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend


volumes:
  pgdata: